export const MAX_VISIBLE_NOTIFICATION_POPUPS = 3
export const NOTIFICATION_BURST_WINDOW_MS = 4_000
export const NOTIFICATION_POPUP_DURATION_MS = 8_000
export const NOTIFICATION_PREVIEW_CODE_POINTS = 180
export const NOTIFICATION_DEDUPLICATION_CAPACITY = 1_000
export const NOTIFICATION_PAGE_SIZE = 30
export const NOTIFICATION_REFRESH_DEBOUNCE_MS = 250
